# actionlint configuration
# See https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Path-specific configurations.
paths:
  # Glob pattern relative to the repository root for matching files. The path separator is always '/'.
  # This example configures any YAML file under the '.github/workflows/' directory.
  .github/workflows/**/*.{yml,yaml}:
    # List of regular expressions to filter errors by the error messages.
    ignore:
      # Ignore the specific error from shellcheck which trips up on `run: |` blocks.
      - 'shellcheck reported issue in this script: SC2086:.+'
