# Example: How to use the reusable security hardening workflow in another project

name: Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Run weekly on Mondays at 2 AM UTC
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Type of security scan to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - sast-only
          - container-only
          - infrastructure-only

jobs:
  security-hardening:
    name: Security Hardening
    uses: huntridge-labs/hardening-workflows/.github/workflows/reusable-security-hardening.yml@main
    with:
      scan_type: ${{ github.event.inputs.scan_type || 'full' }}
      python_version: '3.11'
      aws_region: 'us-west-2'
      post_pr_comment: true
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      security-events: write
      actions: read
      pull-requests: write
      checks: write
      id-token: write