"""Report generation for hardening scan results."""

import json
from datetime import datetime, timezone
from typing import Any

from .models import HardeningReport, ScanResult, Finding, Severity


class ReportGenerator:
    """Generate reports in multiple formats."""

    def __init__(self, report: HardeningReport):
        self.report = report

    def generate_markdown(self, include_details: bool = True) -> str:
        """Generate markdown report suitable for PR comments."""
        lines = [
            "# Security Hardening Report",
            "",
            f"**Repository:** {self.report.repository or 'N/A'}",
            f"**Branch:** {self.report.branch or 'N/A'}",
            f"**Commit:** {self.report.commit_sha[:8] if self.report.commit_sha else 'N/A'}",
            f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
            "",
            "## Summary",
            "",
            "| Severity | Count |",
            "|----------|-------|",
            f"| Critical | {self.report.critical_count} |",
            f"| High | {self.report.high_count} |",
            f"| Medium | {self.report.medium_count} |",
            f"| Low | {self.report.low_count} |",
            f"| **Total** | **{self.report.total_findings}** |",
            "",
        ]

        # Overall status
        if self.report.total_findings == 0:
            lines.append("**Status:** All scans passed with no findings")
        elif self.report.critical_count > 0 or self.report.high_count > 0:
            lines.append("**Status:** Action required - high/critical severity findings detected")
        else:
            lines.append("**Status:** Review recommended - findings detected")

        lines.append("")
        lines.append("## Scanner Results")
        lines.append("")

        # Per-scanner summary
        for result in self.report.results:
            status_icon = self._get_status_icon(result)
            counts = result.finding_counts
            count_str = f"{len(result.findings)} findings" if result.findings else "No findings"

            lines.append(f"### {status_icon} {result.scanner}")
            lines.append("")

            if result.error_message:
                lines.append(f"**Error:** {result.error_message}")
            else:
                lines.append(f"**Findings:** {count_str}")

                if result.findings and include_details:
                    lines.append("")
                    lines.append("<details>")
                    lines.append(f"<summary>View {len(result.findings)} findings</summary>")
                    lines.append("")
                    lines.append("| Severity | Rule | File | Message |")
                    lines.append("|----------|------|------|---------|")

                    # Sort by severity (critical first)
                    sorted_findings = sorted(
                        result.findings,
                        key=lambda f: f.severity.value,
                        reverse=True
                    )

                    for finding in sorted_findings[:50]:  # Limit to 50
                        sev_icon = self._severity_icon(finding.severity)
                        file_loc = f"{finding.file_path}"
                        if finding.line_number:
                            file_loc += f":{finding.line_number}"
                        msg = finding.message[:60] + "..." if len(finding.message) > 60 else finding.message
                        msg = msg.replace("|", "\\|").replace("\n", " ")
                        lines.append(f"| {sev_icon} | `{finding.rule_id}` | `{file_loc}` | {msg} |")

                    if len(result.findings) > 50:
                        lines.append(f"| ... | ... | ... | *{len(result.findings) - 50} more findings* |")

                    lines.append("")
                    lines.append("</details>")

            lines.append("")

        # Footer
        lines.extend([
            "---",
            "*Generated by [Hardening Workflows](https://github.com/huntridge-labs/hardening-workflows)*",
        ])

        return "\n".join(lines)

    def generate_json(self) -> str:
        """Generate JSON report."""
        data = {
            "metadata": {
                "repository": self.report.repository,
                "branch": self.report.branch,
                "commit_sha": self.report.commit_sha,
                "generated_at": datetime.now(timezone.utc).isoformat(),
            },
            "summary": {
                "total_findings": self.report.total_findings,
                "critical": self.report.critical_count,
                "high": self.report.high_count,
                "medium": self.report.medium_count,
                "low": self.report.low_count,
            },
            "scanners": [],
        }

        for result in self.report.results:
            scanner_data = {
                "name": result.scanner,
                "success": result.success,
                "error": result.error_message,
                "finding_count": len(result.findings),
                "findings": [f.to_dict() for f in result.findings],
            }
            data["scanners"].append(scanner_data)

        return json.dumps(data, indent=2)

    def generate_sarif(self) -> str:
        """Generate combined SARIF report."""
        sarif = {
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [],
        }

        for result in self.report.results:
            run = {
                "tool": {
                    "driver": {
                        "name": f"hardening-{result.scanner}",
                        "version": "2.10.0",
                        "informationUri": "https://github.com/huntridge-labs/hardening-workflows",
                        "rules": self._extract_rules(result.findings),
                    }
                },
                "results": self._findings_to_sarif_results(result.findings),
            }
            sarif["runs"].append(run)

        return json.dumps(sarif, indent=2)

    def _extract_rules(self, findings: list[Finding]) -> list[dict]:
        """Extract unique rules from findings."""
        rules = {}
        for f in findings:
            if f.rule_id not in rules:
                rules[f.rule_id] = {
                    "id": f.rule_id,
                    "shortDescription": {"text": f.rule_id},
                    "properties": {
                        "security-severity": str(self._severity_to_cvss(f.severity)),
                    },
                }
        return list(rules.values())

    def _findings_to_sarif_results(self, findings: list[Finding]) -> list[dict]:
        """Convert findings to SARIF results."""
        results = []
        for f in findings:
            result = {
                "ruleId": f.rule_id,
                "level": self._severity_to_sarif_level(f.severity),
                "message": {"text": f.message},
                "locations": [
                    {
                        "physicalLocation": {
                            "artifactLocation": {"uri": f.file_path},
                            "region": {"startLine": max(1, f.line_number)},
                        }
                    }
                ],
            }
            results.append(result)
        return results

    def _get_status_icon(self, result: ScanResult) -> str:
        """Get status icon for scanner result."""
        if result.error_message:
            return "Error"
        if not result.findings:
            return "Passed"
        counts = result.finding_counts
        if counts.get("critical", 0) > 0 or counts.get("high", 0) > 0:
            return "Failed"
        return "Warning"

    def _severity_icon(self, severity: Severity) -> str:
        """Get icon for severity level."""
        icons = {
            Severity.CRITICAL: "CRITICAL",
            Severity.HIGH: "HIGH",
            Severity.MEDIUM: "MEDIUM",
            Severity.LOW: "LOW",
            Severity.NONE: "INFO",
        }
        return icons.get(severity, "UNKNOWN")

    def _severity_to_sarif_level(self, severity: Severity) -> str:
        """Convert severity to SARIF level."""
        mapping = {
            Severity.CRITICAL: "error",
            Severity.HIGH: "error",
            Severity.MEDIUM: "warning",
            Severity.LOW: "note",
            Severity.NONE: "none",
        }
        return mapping.get(severity, "warning")

    def _severity_to_cvss(self, severity: Severity) -> float:
        """Convert severity to approximate CVSS score."""
        mapping = {
            Severity.CRITICAL: 9.5,
            Severity.HIGH: 7.5,
            Severity.MEDIUM: 5.0,
            Severity.LOW: 2.5,
            Severity.NONE: 0.0,
        }
        return mapping.get(severity, 5.0)
