name: Infrastructure Security Scanner

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      iac_path:
        description: 'Relative path to the infrastructure-as-code directory to scan'
        required: false
        type: string
        default: 'infrastructure'
      python_version:
        description: 'Python version to use for IaC scanners'
        required: false
        type: string
        default: '3.12'
      aws_region:
        description: 'AWS region used for IaC tooling that requires region context'
        required: false
        type: string
        default: 'us-east-1'
      enable_code_security:
        description: 'Whether GitHub Code Security is enabled for this repository'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

env:
  PYTHON_VERSION: ${{ inputs.python_version }}
  AWS_REGION: ${{ inputs.aws_region }}

jobs:
  infrastructure-security:
    name: Infrastructure Security Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Prepare infrastructure scan directory
      run: |
        IAC_PATH="${{ inputs.iac_path }}"
        if [ -z "$IAC_PATH" ]; then
          IAC_PATH='infrastructure'
        fi

        if [ ! -d "$IAC_PATH" ]; then
          echo "⚠️  Directory '$IAC_PATH' not found. Skipping infrastructure scans."
          exit 0
        fi

        mkdir -p "$IAC_PATH"/security-reports
        echo "📁 Created security reports directory: $IAC_PATH/security-reports"

    - name: Run Trivy Infrastructure Scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'config'
        scan-ref: '${{ inputs.iac_path }}'
        format: 'sarif'
        output: '${{ inputs.iac_path }}/security-reports/trivy-results.sarif'
        hide-progress: true
      continue-on-error: true

    - name: Run Checkov Infrastructure Scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ inputs.iac_path }}
        framework: terraform
        output_format: sarif, json
        output_file_path: ${{ inputs.iac_path }}/security-reports/checkov-results.sarif,${{ inputs.iac_path }}/security-reports/checkov-results.json
      continue-on-error: true

    - name: Upload infrastructure SARIF results
      uses: github/codeql-action/upload-sarif@v3
      if: inputs.enable_code_security == true && always() && github.actor != 'nektos/act'
      with:
        sarif_file: ${{ inputs.iac_path }}/security-reports/trivy-results.sarif
        category: infrastructure-trivy
      continue-on-error: true

    - name: Upload Checkov SARIF results
      uses: github/codeql-action/upload-sarif@v3
      if: inputs.enable_code_security == true && always() && github.actor != 'nektos/act' && hashFiles('${{ inputs.iac_path }}/security-reports/checkov-results.sarif') != ''
      with:
        sarif_file: ${{ inputs.iac_path }}/security-reports/checkov-results.sarif
        category: infrastructure-checkov
      continue-on-error: true

    - name: Upload infrastructure artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: infrastructure-security-reports
        path: |
          ${{ inputs.iac_path }}/security-reports/
        retention-days: 30
