name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Type of release (patch, minor, major, prerelease)'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
          - prerelease
      dryRun:
        description: 'Dry run (preview only, no actual release)'
        required: false
        default: true
        type: boolean

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://github.com/${{ github.repository }}/releases/latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: ${{ github.event.inputs.dryRun != 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Release (Auto)
        if: github.event_name == 'push' || github.event.inputs.releaseType == 'auto'
        run: npm run release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release (Specific Type)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.releaseType != 'auto'
        run: npm run release:ci -- ${{ github.event.inputs.releaseType }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dry-run:
    name: Release Preview (Dry Run)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ github.event.inputs.dryRun == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Release Preview
        run: npm run release:dry

  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    needs: release
    if: success()

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run security audit
        run: npm audit --audit-level=high

      - name: Check for vulnerabilities
        run: |
          if npm audit --audit-level=high --json | jq '.vulnerabilities | length' | grep -q '^0$'; then
            echo "✅ No high-severity vulnerabilities found"
          else
            echo "❌ High-severity vulnerabilities detected"
            exit 1
          fi
