name: Generate SBOM

on:
  workflow_call:
    inputs:
      enable_code_security:
        description: 'Whether GitHub Code Security is enabled for this repository'
        required: false
        type: boolean
        default: false
      output-path:
        required: false
        type: string
        default: sbom.syft.json
      scan-path:
        description: 'Directory or file path to scan'
        required: false
        type: string
        default: '.'
      scan-image:
        description: 'Container image to scan'
        required: false
        type: string

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine scan target
        id: target
        run: |
          if [ -n "${{ inputs.scan-image }}" ]; then
            echo "target=${{ inputs.scan-image }}" >> $GITHUB_OUTPUT
            echo "type=image" >> $GITHUB_OUTPUT
          else
            echo "target=${{ inputs.scan-path }}" >> $GITHUB_OUTPUT
            echo "type=path" >> $GITHUB_OUTPUT
          fi

      - name: Generate CycloneDX JSON SBOM
        uses: anchore/sbom-action@v0.16.0
        if: steps.target.outputs.type == 'path'
        with:
          path: ${{ steps.target.outputs.target }}
          format: cyclonedx-json
          output-file: ${{ inputs.output-path }}

      - name: Generate CycloneDX JSON SBOM
        uses: anchore/sbom-action@v0.16.0
        if: steps.target.outputs.type == 'image'
        with:
          image: ${{ steps.target.outputs.target }}
          format: cyclonedx-json
          output-file: ${{ inputs.output-path }}

      - name: Create SBOM Summary
        run: |
          echo "<details>" > sbom.md
          echo "<summary>🔍 SBOM Details</summary>" >> sbom.md
          echo "" >> sbom.md
          echo "## 📦 SBOM Summary" >> sbom.md
          echo "" >> sbom.md
          echo "**Generated by:** Syft v0.16.0" >> sbom.md
          echo "**Formats:**" >> sbom.md
          echo "- CycloneDX JSON: \`${{ inputs.output-path }}\`" >> sbom.md
          echo "" >> sbom.md
          echo "### Artifact Details" >> sbom.md
          echo "- The SBOM is attached as a workflow artifact under **sbom-artifacts-${{ github.run_id }}**." >> sbom.md
          echo "- Container image SBOM artifacts are named **container-scan-results-sbom-image-name**" >> sbom.md
          echo "" >> sbom.md
          echo "You can import the JSON into a CycloneDX viewer / Dependency-Track." >> sbom.md
          echo "</details>" >> sbom.md
          
      - name: Upload SBOM Summary
        uses: actions/upload-artifact@v4
        with:
          name: scanner-summary-sbom
          path: sbom.md
