name: Generate SBOM

on:
  workflow_call:
    inputs:
      enable_code_security:
        description: 'Whether GitHub Code Security is enabled for this repository'
        required: false
        type: boolean
        default: false
      output-path:
        required: false
        type: string
        default: sbom.syft.json

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate CycloneDX JSON SBOM
        uses: anchore/sbom-action@v0.16.0
        with:
          format: cyclonedx-json
          output-file: ${{ inputs.output-path }}

      - name: Generate human-readable SBOM
        run: |
          echo "Generating human-readable SBOM (table format)..."
          syft . -o table > sbom.table.txt
          head -n 20 sbom.table.txt  # show preview in logs

      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifacts-${{ github.run_id }}
          path: |
            ${{ inputs.output-path }}
            sbom.table.txt

      - name: Create SBOM Summary
        run: |
          echo "<details>" > sbom.md
          echo "<summary>SBOM Details</summary>" >> sbom.md
          echo "" >> sbom.md
          echo "## 📦 SBOM Summary" >> sbom.md
          echo "" >> sbom.md
          echo "**Generated by:** Syft v0.16.0" >> sbom.md
          echo "**Formats:**" >> sbom.md
          echo "- CycloneDX JSON: \`${{ inputs.output-path }}\`" >> sbom.md
          echo "- Human-readable Table: \`sbom.table.txt\`" >> sbom.md
          echo "" >> sbom.md
          echo "### Artifact Details" >> sbom.md
          echo "- Both SBOMs are attached as workflow artifacts under **sbom-artifacts-${{ github.run_id }}**." >> sbom.md
          echo "" >> sbom.md
          echo "You can view dependencies directly in \`sbom.table.txt\` or import the JSON into a CycloneDX viewer / Dependency-Track." >> sbom.md
          echo "</details>" >> sbom.md
          
      - name: Upload SBOM Summary
        uses: actions/upload-artifact@v4
        with:
          name: scanner-summary-sbom
          path: sbom.md
