name: Generate SBOM

on:
  workflow_call:
    inputs:
      enable_code_security:
        description: 'Whether GitHub Code Security is enabled for this repository'
        required: false
        type: boolean
        default: false
      scan-path:
        description: 'Directory or file path to scan'
        required: false
        type: string
        default: '.'
      scan-image:
        description: 'Container image to scan'
        required: false
        type: string

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine scan target
        id: target
        run: |
          if [ -n "${{ inputs.scan-image }}" ]; then
            target="${{ inputs.scan-image }}"
            type="image"
            prefix=$(echo "$target" | sed 's/:/-/g' | sed 's/\//-/g')
          else
            target="${{ inputs.scan-path }}"
            type="path"
            prefix=$(basename "$target")
          fi
          mkdir -p .syft/sboms
          output_file=".syft/sboms/${prefix}.json"
          echo "target=$target" >> $GITHUB_OUTPUT
          echo "type=$type" >> $GITHUB_OUTPUT
          echo "prefix=$prefix" >> $GITHUB_OUTPUT
          echo "output_file=$output_file" >> $GITHUB_OUTPUT

      - name: Generate CycloneDX JSON Path SBOM
        uses: anchore/sbom-action@v0.16.0
        if: steps.target.outputs.type == 'path'
        with:
          path: ${{ steps.target.outputs.target }}
          format: cyclonedx-json
          output-file: ${{ steps.target.outputs.output_file }}

      - name: Generate CycloneDX JSON Image SBOM
        uses: anchore/sbom-action@v0.16.0
        if: steps.target.outputs.type == 'image'
        with:
          image: ${{ steps.target.outputs.target }}
          format: cyclonedx-json
          output-file: ${{ steps.target.outputs.output_file }}

      - name: Create SBOM Summary
        run: |
          echo "<details>" > sbom.md
          echo "<summary>🔍 SBOM Details</summary>" >> sbom.md
          echo "" >> sbom.md
          echo "## 📦 SBOM Summary" >> sbom.md
          echo "" >> sbom.md
          echo "**Generated by:** Syft v0.16.0" >> sbom.md
          echo "**Formats:**" >> sbom.md
          echo "- CycloneDX JSON: \`${{ steps.target.outputs.output_file }}\`" >> sbom.md
          echo "" >> sbom.md
          echo "### Artifact Details" >> sbom.md
          echo "- The SBOM is attached as a workflow artifact under **sbom-artifacts-${{ github.run_id }}**." >> sbom.md
          echo "- Container image SBOM artifacts are named **container-scan-results-sbom-image-name**" >> sbom.md
          echo "" >> sbom.md
          echo "You can import the JSON into a CycloneDX viewer / Dependency-Track." >> sbom.md
          echo "</details>" >> sbom.md

      - name: Upload SBOM Summary
        uses: actions/upload-artifact@v4
        with:
          name: scanner-summary-sbom
          path: sbom.md
