name: Simple Reusable Security Test

on:
  workflow_call:
    inputs:
      scan_type:
        description: 'Type of security scan to run'
        required: false
        default: 'full'
        type: string
      python_version:
        description: 'Python version to use'
        required: false
        default: '3.12'
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        description: 'AWS Account ID for infrastructure scans'
        required: false
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Type of security scan to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - sast-only
          - container-only
          - infrastructure-only

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write
  checks: write

jobs:
  test-reusable:
    name: Test Reusable Workflow
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Test Configuration
      run: |
        echo "🧪 Testing Reusable Workflow Configuration"
        echo "Scan Type: ${{ inputs.scan_type || github.event.inputs.scan_type }}"
        echo "Python Version: ${{ inputs.python_version || github.event.inputs.python_version || '3.12' }}"
        echo "Event Name: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "✅ Triggered manually via workflow_dispatch"
        elif [ "${{ github.event_name }}" = "workflow_call" ]; then
          echo "✅ Called by another workflow via workflow_call"
        else
          echo "ℹ️ Triggered by: ${{ github.event_name }}"
        fi
        
        echo ""
        echo "🎯 This demonstrates the reusable workflow is working correctly!"
        echo "📋 Next step: Replace this with the full security pipeline once validated"
    
    - name: Validate Inputs
      run: |
        SCAN_TYPE="${{ inputs.scan_type || github.event.inputs.scan_type }}"
        PYTHON_VER="${{ inputs.python_version || github.event.inputs.python_version || '3.12' }}"
        
        echo "Final resolved values:"
        echo "- Scan Type: $SCAN_TYPE"
        echo "- Python Version: $PYTHON_VER"
        
        if [ -z "$SCAN_TYPE" ]; then
          echo "❌ ERROR: No scan type specified"
          exit 1
        fi
        
        echo "✅ All inputs validated successfully"