name: Test Simple Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Type of security scan to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - sast-only
          - container-only
          - infrastructure-only

jobs:
  test-simple-reusable:
    name: Test Simple Reusable
    uses: ./.github/workflows/simple-reusable-test.yml
    with:
      scan_type: ${{ github.event.inputs.scan_type || 'full' }}
      python_version: '3.11'
    permissions:
      contents: read
      security-events: write
      actions: read
      pull-requests: write
      checks: write

  comparison-note:
    name: Simple Test Complete
    runs-on: ubuntu-latest
    needs: test-simple-reusable
    if: always()
    
    steps:
    - name: Test Summary
      run: |
        echo "🧪 Simple Reusable Workflow Test Complete!"
        echo ""
        echo "If you can see this message, the basic reusable workflow pattern works."
        echo "Once this is validated, we can replace the simple test with the full security pipeline."
        echo ""
        echo "Status: ${{ needs.test-simple-reusable.result }}"